image: python:3.12

stages:
  - lint
  - audit
  - test
  - docker-build
  - deploy

cache:
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install ruff
    - ruff check .

audit:
  stage: audit
  script:
    - pip install pip-audit
    - pip-audit
    

test:
  stage: test
  script:
    - pip install pytest
    - pytest

docker-build-job:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script: []
  script:
    - docker build -t mon-app:latest .
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application"
    - echo "Image Docker prête à être déployée"
  only:
    - main